<!DOCTYPE html>
<html>

<head lang="en">
    <meta charset="UTF-8">
    <title>sample-app</title>
    <!-- build:css assets/styles/vendor.css -->
    <!-- bower:css -->
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    <!-- endbower -->
    <!-- endbuild -->

    <!-- build:css assets/styles/main.css -->
    <link rel="stylesheet" type="text/css" href="./assets/css/style.css" media="screen" />
    <!-- endbuild -->

</head>

<body>

    <div class="container">

        <div class="row">

            <div class="col-md-12" style="text-align: center;">
                <h1>sample-app</h1>
                <p>This is my website.</p>
                <p>There are many like it, but this one is mine.</p>
            </div>

        </div>

    </div>
    <!-- build:js scripts/vendor.js -->
    <!-- bower:js -->
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/angularjs/angular.js"></script>
    <!-- endbower -->
    <!-- endbuild -->

    <!-- build:js scripts/app.js -->
    <!-- !DO NOT EDIT! autogenerated includes, see Gruntfile.js -->
    <!-- include: "type": "js", "files": "<%= app.scripts %>" -->
    <script src="assets/js/bar.js"></script>
    <script src="assets/js/foo.js"></script>
    <!-- /include -->
    <!-- endbuild -->

</body>

</html>
